version: '2'

services:
    # basenode:
    #     build: ./base
    #    image: settlemint/base-multichain    
    #     stdin_open: true
    #     tty: true
    masternode:
        build: ./master
        image: settlemint/master-multichain
        stdin_open: true
        tty: true
        expose:
            - 7557
            - 8002
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
    slavenode:
        build: ./node
        image: settlemint/node-multichain
        stdin_open: true
        tty: true
        expose:
            - 7557
            - 8002
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode
    explorernode:
        build: ./explorer
        image: settlemint/explorer-multichain
        stdin_open: true
        tty: true
        expose:
            - 2750
            - 7557
            - 8002
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichainrpc
            RPC_PASSWORD: this-is-insecure-change-it
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
            VIRTUAL_HOST: explorer.multichain.docker
            VIRTUAL_PORT: 2750
        links:
            - masternode
        depends_on:
            - masternode
